### ISSUE TITLE
Transfer Funds screen: Position of 'Cancel' button

### ISSUE THREAD

**Issue by najiha2002** [najiha2002/ATMInterface#6]
For the cancel button, I believe it will provide a better experience if we position it at the left.

For reference:
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/63440340/200101910-b652ad97-7deb-41bd-8266-21f2161b501b.png">

**Comment by ffarahh** [comment]
okay we will reconsider that  in meeting later before implementation phase occur

**Comment by ffarahh** [comment]
Updated
